version: "2.2"
services:
  db:
    image: postgres
    restart: always
    env_file:
      - ./.env
    container_name: postgres
    ports:
      - '5432:5432'

  server:
    build: ./server
    container_name: eec-server
    volumes:
      - /app/server
    command: npm run start:pm2-runtime
    env_file:
      - ./server/.env.prod
    ports:
      - 8080:8080
    environment:
      NODE_ENV: production
    depends_on:
      - db
      
  client:
    build: ./client
    container_name: eec-client
    volumes:
      - /app/client
    env_file:
      - ./client/.env.local
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
    depends_on:
      - server

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    env_file:
      - ./.env
    ports:
      - '5050:80'
    depends_on:
      - db