import './globals.css';
import SideBar from '@/components/SideBar';
import Link from 'next/link';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <div className="flex">
          <SideBar />
          <div className="bg-[#EDEFF3] w-full flex flex-col pb-6">
            <div className="flex w-full h-14 py-4 flex-row-reverse px-6">
              <div>
                <i />
                <Link href="/login">
                  로그인
                </Link>
              </div>
              <div className="mr-3">
                <i />
                <Link href="/signup">
                  회원가입
                </Link>
              </div>
            </div>
            <div className="bg-white mx-6 rounded-sm h-full">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
