import './globals.css';
import SideBar from '@/components/SideBar';
import Link from 'next/link';
import Nav from '@/components/Nav';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <div className="flex">
          <SideBar />
          <div className="bg-[#EDEFF3] w-full flex flex-col pb-6">
            <Nav />
            <div className="bg-white mx-6 rounded-sm h-full">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
